- name: Install Redis Server
  apt:
    name: redis
    state: present
    update_cache: yes

- name: Update Redis config from Local address to 0.0.0.0
  replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis
  systemd:
    name: redis
    state: restarted
    enabled: yes

- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node-exporter