- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Download {{COMPONENT}} from Nexus
  get_url:
    url: http://172.31.8.2:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APPVERSION}}.zip
    dest: /var/www/html/{{COMPONENT}}.zip
    username: admin
    password: admin

- name: Unzip the Downloaded Content
  unarchive:
    src: /var/www/html/{{COMPONENT}}.zip
    dest: /var/www/html/
    remote_src: yes

- name: Remove default files
  file:
    path: "{{ item }}"
    state: absent
  loop:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available/default

- name: Copy config file
  template:
    src: todo.conf
    dest: /etc/nginx/sites-enabled/todo.conf

- name: Start Nginx
  systemd:
    state: restarted
    name: nginx
    enabled: yes

- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node-exporter

- name: Install Filebeat Monitoring
  include_role:
    name: common
    tasks_from: filebeat
