- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Start Nginx
  systemd:
    state: started
    name: nginx
    enabled: yes

- name: including role
  include_role:
    name: common
    tasks_from: nexus-download-component

- name: Remove default files
  file:
    path: "{{ item }}"
    state: absent
  loop:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available/default

- name: Copy config file
  template:
    src: todo.conf
    dest: /etc/nginx/sites-enabled/todo.conf

- name: Start Nginx
  systemd:
    state: started
    name: nginx
    enabled: yes
