- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present
- name: Download Frontend from Nexus
  git:
      repo: 'https://github.com/naveenzelarsoft/frontend.git'
      dest: /root/frontend
#- name: Unzip the Downloaded Content
 # unarchive:
  #  src: /root/frontend.zip
  #  dest: /root/frontend
   # remote_src: yes

- name: Replace content
  replace:
    path: /etc/nginx/sites-available/default
    regexp: '/var/www/html'
    replace: '/root/frontend/dist'
- name: Start Nginx
  systemd:
    state: started
    name: nginx
    enabled: yes