- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Download frontend from Nexus
  get_url:
    url: http://3.227.21.179:8081/repository/frontend/frontend-0.0.1.zip
    dest: /root/frontend.zip
    username: admin
    password: admin

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/frontend.zip
    dest: /root/
    remote_src: yes

- name: Replace content
  replace:
    path: /etc/nginx/sites-available/default
    regexp: '/var/www/html'
    replace: '/root/frontend/dist'

- name: Start Nginx
  systemd:
    state: started
    name: nginx
    enabled: yes

- name: Replace content
  replace:
    path: /root/config/index.js
    regexp: '127.0.0.1'
    replace: 'login.naveenbommakanti.uk'

- name: Replace content
  replace:
    path: /root/config/index.js
    regexp: '127.0.0.2'
    replace: 'todo.naveenbommakanti.uk'

- name: To start npm
  shell: npm start
  args:
    chdir: /root/