- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Start Nginx
  systemd:
    state: started
    name: nginx
    enabled: yes

- name: including role
  include_role:
    name: common
    tasks_from: nexus-download-component