- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Replace content
  replace:
    path: /etc/nginx/sites-available/default
    regexp: '/var/www/html'
    replace: '/root/frontend/dist'

- name: Start Nginx
  systemd:
    state: started
    name: nginx
    enabled: yes

- name: including role
  include_role:
    name: common
    tasks_from: nexus-download-component

- name: Replace content
  replace:
    path: /root/config/index.js
    regexp: '127.0.0.1'
    replace: 'login.naveenbommakanti.uk'

- name: Replace content
  replace:
    path: /root/config/index.js
    regexp: '127.0.0.2'
    replace: 'todo.naveenbommakanti.uk'

- name: To start npm
  shell: npm start
  args:
    chdir: /root/