- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: including role
  iclude_role:
    name: common
    tasks_from: nexus-download-component

- name: including role
  iclude_role:
    name: common
    tasks_from: start-service