- name: Install dependencies
  apt:
    name: golang
    update_cache: yes
    state: present

- name: including role
  include_role:
    name: common
    tasks_from: nexus-download-component

- name: including role
  include_role:
    name: common
    tasks_from: start-service

- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node-exporter

- name: Install Filebeat Monitoring
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    IS_STRUCTURED: true
    LOG_FILES:
      - { file: "/var/log/{{COMPONENT}}.log", type: "login" }
