- name: Install dependencies
  apt:
    name: golang
    update_cache: yes
    state: present

- name: Download login  from Nexus
  get_url:
    url: http://34.205.27.64:8081/repository/login/login-0.0.1.zip
    dest: /root/login.zip
    username: admin
    password: admin

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/login.zip
    dest: /root/
    remote_src: yes

- name: Copy login Service file
  ansible.builtin.copy:
    src: /root/login.service
    dest: /etc/systemd/system/login.service
    remote_src: yes

- name: Start login Service
  systemd:
    name: "login"
    daemon_reload: yes
    state: started
    enabled: yes