- name: Install dependencies
  apt:
    name: golang
    update_cache: yes
    state: present
- name: Download Frontend from Nexus
  git:
    repo: https://github.com/naveenzelarsoft/login.git
    dest: /root/login
    #- name: Unzip the Downloaded Content
    # unarchive:
    #  src: /root/login
    #  dest: /root/login
    # remote_src: yes

- name: Copy login Service file
  file:
    src: /root/login/login.service
    dest: /etc/systemd/system/login.service

- name: Start login Service
  systemd:
    name: "login"
    daemon_reload: yes
    state: started
    enabled: yes