- name: Install dependencies
  apt:
    name: golang
    update_cache: yes
    state: present
- name: Download Frontend from Nexus
  get_url:
    url: https://github.com/naveenzelarsoft/login.git
    dest: /root/login
    username: admin
    password: admin
    #- name: Unzip the Downloaded Content
    # unarchive:
    #  src: /root/frontend.zip
    #  dest: /root/frontend
    # remote_src: yes

- name: Copy {{COMPONENT}} Service file
  template:
    src: "login.service"
    dest: /etc/systemd/system/login.service

- name: Start {{COMPONENT}} Service
  systemd:
    name: "login"
    daemon_reload: yes
    state: started
    enabled: yes