- name: Download {{COMPONENT}} from Nexus
  get_url:
    url: http://3.239.162.87:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APPVERSION}}.zip
    dest: /root/{{COMPONENT}}.zip
    username: admin
    password: admin

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/{{COMPONENT}}.zip
    dest: /root/
    remote_src: yes