- name: Download frontend from Nexus
  get_url:
    url: http://34.205.27.64:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APPVERSION}}.zip
    dest: /root/{{COMPONENT}}.zip
    username: admin
    password: admin